### ISSUE TITLE
Publish into VS Code Extension Marketplace

### ISSUE THREAD

**Issue by leocaseiro** [weinand/vscode-processes#4]
Hi @weinand, first of all, I would like to thank you for this amazing Extension. I'm mind blown here how awesome this is.

I was just wondering if you have plans to publish into the Marketplace, as I had to set up for some junior developers here and would be easier just install from VsCode Marketplace.

Many Thanks

**Comment by weinand** [comment]
@leocaseiro since the main purpose of the functionality provided by vscode-processes is for diagnostics and trouble shooting, we are currently merging this into VS Code core, so that it is available even in case of problems, for instance if the extension host is unresponsive.

That's the reason why we did not publish vscode-processes to the Marketplace.

**Comment by antoinerousseau** [comment]
@weinand has this been merged into VS Code core? If so, how do I access it? It looks useful!

Edit: my bad, found it!

![Capture d'écran 2019-06-20 18 12 21](https://user-images.githubusercontent.com/160279/59864393-feb9c900-9386-11e9-8082-c5b89f9036f1.png)
